name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
           curl -OL https://firebase.google.com/download/ios
           unzip ios 'Firebase/Firebase.h' 'Firebase/FirebaseAuth/*' 'Firebase/FirebaseFunctions/*' 'Firebase/FirebaseAnalytics/*' 'Firebase/FirebaseDatabase/*'
           rm ios
           touch GoogleService-Info.plist
           xcodebuild clean analyze archive -project Bartender.xcodeproj -scheme Bartender ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
